### ISSUE TITLE
Does the code using the smallest polar diameter in each sector as the paper describes when doing the fast yaw angle calculate?

### ISSUE THREAD

**Issue by oldwalkman** [lilin-hitcrt/SSC#2]
hi, thanks for your excellent work, I have a question when I reading the code， why the code of finding the shortest range point is commented out and then the ssc_dis is determined by the iteration sequence of all the points? It seems it will use the lastest point in the iteration.
`
            // if(ssc_dis.at<cv::Vec4f>(0, sector_id)[3]<10||distance<ssc_dis.at<cv::Vec4f>(0, sector_id)[0]){
            ssc_dis.at<cv::Vec4f>(0, sector_id)[0] = distance;
            ssc_dis.at<cv::Vec4f>(0, sector_id)[1] = filtered_pointcloud->points[i].x;
            ssc_dis.at<cv::Vec4f>(0, sector_id)[2] = filtered_pointcloud->points[i].y;
            ssc_dis.at<cv::Vec4f>(0, sector_id)[3] = label;
            // }
`

**Comment by lilin-hitcrt** [comment]
> hi, thanks for your excellent work, I have a question when I reading the code， why the code of finding the shortest range point is commented out and then the ssc_dis is determined by the iteration sequence of all the points? It seems it will use the lastest point in the iteration.
> `// if(ssc_dis.at<cv::Vec4f>(0, sector_id)[3]<10||distance<ssc_dis.at<cv::Vec4f>(0, sector_id)[0]){ ssc_dis.at<cv::Vec4f>(0, sector_id)[0] = distance; ssc_dis.at<cv::Vec4f>(0, sector_id)[1] = filtered_pointcloud->points[i].x; ssc_dis.at<cv::Vec4f>(0, sector_id)[2] = filtered_pointcloud->points[i].y; ssc_dis.at<cv::Vec4f>(0, sector_id)[3] = label; // }`

Thanks for your question!
In fact, the results in our paper are based on the shortest range. However, recently we found that using the shortest range is not the best strategy. We found that using random points (the last point, not strictly random) can slightly improve the effect of the algorithm. We guess this is because the nearest point is easily disturbed by noisy data. Of course, random selection (the last point) is not the best strategy. We are also trying other strategies, such as using cluster centers as representative points. If you have better ideas, please feel free to contact us.

**Comment by lilin-hitcrt** [comment]
Since there is no further update about this issue, I will close it. If you have any questions, please feel free to reopen it.
